name: Windows (CMake)

on: [push, workflow_dispatch]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        path: wxfb

    - name: Install Tools
      shell: cmd
      run: |
        choco install cmake -y --no-progress --version=3.19.2 --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Download wxWidgets
      shell: cmd
      run: |
        curl -L --output wxdev.7z https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.4/wxMSW-3.1.4_vc14x_x64_Dev.7z
        7z x wxdev.7z -o./wx/
        curl -L --output wxheaders.7z https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.4/wxWidgets-3.1.4-headers.7z
        7z x wxheaders.7z -o./wx/
        curl -L --output wxrelease.7z https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.4/wxMSW-3.1.4_vc14x_x64_ReleaseDLL.7z
        7z x wxrelease.7z -o./wx/
        
    - name: Configure CMake
      shell: cmd
      run: |
        mkdir ./wxfb/build/cmake
        cmake -S ./wxfb/ -B ./wxfb/build/cmake -DwxWidgets_ROOT_DIR:PATH=%GITHUB_WORKSPACE%/wx/ -DwxWidgets_LIB_DIR:PATH=%GITHUB_WORKSPACE%/wx/lib/vc14x_x64_dll/ -DwxWidgets_USE_REL_AND_DBG:BOOL=OFF -DwxWidgets_CONFIGURATION:STRING=mswu

    - name: Build
      shell: cmd
      run: cmake --build wxfb/build/cmake --parallel --config %BUILD_TYPE%
