name: Windows (CMake)

on: [push, workflow_dispatch]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Tools
      shell: cmd
      run: |
        choco install cmake -y --no-progress --version=3.19.2 --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Download wxWidgets
      shell: cmd
      run: |
        curl -L --output wxdev.7z https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.4/wxMSW-3.1.4_vc14x_x64_Dev.7z
        curl -L --output wxheaders.7z https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.4/wxWidgets-3.1.4-headers.7z
        curl -L --output wxrelease.7z https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.4/wxMSW-3.1.4_vc14x_x64_ReleaseDLL.7z

    - name: Create Build Environment
      shell: cmd
      run: cmake -E make_directory ./build/cmake

    - name: Configure CMake
      shell: cmd
      run: cmake -S . -B ./build/cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: cmd
      run: cmake --build build/cmake --parallel --config $BUILD_TYPE
